#!/bin/sh

set -e

lb config noauto \
        --architectures amd64 \
	--apt-indices false \
	--apt-recommends false \
	--binary-images iso \
        --bootappend-live "console=ttyS0,115200 console=tty0 noeject toram live-media=removable boot=live locales=en_US.UTF-8 keyboard-layouts=de" \
        --cache=true \
        --cache-packages true \
        --debian-installer false \
	--distribution stretch \
        --initsystem systemd \
        --system live \
        --memtest none \
        --verbose \
        --iso-application LocalSuperNode \
        --iso-preparer netminion \
        --iso-publisher netminion \
        --iso-volume LocalSuperNode \
	--mirror-bootstrap http://cloudfront.debian.net/debian/ \
	--mirror-binary http://cloudfront.debian.net/debian/ \
	--mirror-binary-security http://cloudfront.debian.net/debian-security/ \
"${@}"

